name: Povarenok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
    
    - name: Get repository code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'corretto'
        cache: maven

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: ./Frontend/package-lock.json

    - name: Backend unit tests
      run: mvn test -Dtest=ru/spbstu/povarenok/*/*
      working-directory: ./Backend

    - name: Frontend unit tests
      run:  |
        npm ci
        npm test
      working-directory: ./Frontend

  integration-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Get repository code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven

    - name: Backend integration tests
      run: mvn test -Dtest="integration/*"
      working-directory: ./Backend

    - name: Server start
      run: mvn spring-boot:run -Dspring-boot.run.arguments=--spring.profiles.active=test &
      working-directory: ./Backend

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.2.0

    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v1.1.0

    - name: Frontend integration tests
      run: |
        rm -rf node_modules  
        npm install
        npm uninstall chromedriver
        npm install chromedriver
        npm run build
        npm run start
        npm ci
        npm run integrtest
      working-directory: ./Frontend