name: Povarenok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
    
    - name: Get repository code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'corretto'
        cache: maven

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: ./Frontend/package-lock.json

    - name: Backend unit tests
      run: mvn test -Dtest=ru/spbstu/povarenok/*/*
      working-directory: ./Backend

    - name: Frontend unit tests
      run:  |
        npm ci
        npm test
      working-directory: ./Frontend

  integration-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Get repository code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven

    - name: Backend integration tests
      run: mvn test -Dtest="integration/*"
      working-directory: ./Backend

    - name: Server start
      run: mvn spring-boot:run -Dspring-boot.run.arguments=--spring.profiles.active=test &
      working-directory: ./Backend

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.2.0
      with:
        chrome-version: latest
    - run: |
        sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
        sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y update
        sudo apt-get -y install google-chrome-stable

    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v1.1.0
    - run: |
        wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        sudo apt-get install xvfb

    - name: Frontend integration tests
      run: |
        npm install  selenium-webdriver chromedriver geckodriver
        npm rebuild
        npm ci
        Xvfb :1 -screen 0 1024x768x24 & export DISPLAY=:1
        npm run integrtest
      working-directory: ./Frontend
