name: Povarenok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unit tests:

    runs-on: ubuntu-latest

    steps:
    
    - name: Get repository code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Backend unit tests
      run: mvn test --file ./Backend/pom.xml

    - name: Frontend unit tests
      run: npm ci
           npm test
